### ISSUE TITLE
Ideas for combining Projects and Assignments

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulib.org#154]
Some ideas about linking Projects and Assignments into something greater.

- [x] Assignments could use existing Projects infrastructure (esp. containers) #302
- [ ] Assignments could be expanded to allow grading of arbitrary projects, for example:
  - Running and/or expecting Tests
  - Generating Tests that check Models
  - Being agnostic of naming.
  - Checking code style, patterns, ...
- [x] Assignments could be expanded to support GUIs (JavaFX)
  - [x] Using Projects, interfaces could be streamed to the browser #265
- [x] Assignments could be integrated with GitHub Classroom #176

General benefits:

- Allows checking of PM / generic assignments without needing to check out
  - No IDE setup required
  - Generally less issues due to shared environment
  - Applies to both students and TAs
- Automatic checking / grading reduces time spent with each submission
